# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


name: loan test pipeline

# variables:  # job-level
#       VERSION: '8.0.0'

resources:
  repositories:
  - repository: ApiWebCombination
    type: github
    ref: refs/heads/master
    name: kms-loantran/Regression-api-web-combination-sample
    endpoint: https://github.com/kms-loantran

trigger:
  - master

pool:
  vmImage: windows-latest

stages:
- stage: Test
  displayName: Run Automation script
  jobs:
  - job: TestOnWindows
    displayName: Run automation script on Windows
    continueOnError: true
    variables:  # job-level
      VERSION: '8.0.0'
    steps:
    - checkout: 
      clean: true
      fetchDepth: 5
    - bash: |
        curl "https://download.katalon.com/${VERSION}/Katalon_Studio_Engine_Windows_64-8.0.0.zip" -o "katalon_runtime_engine.zip" 
      displayName: download KRE package
    - bash: 
        unzip Katalon_Studio_Windows_64-${VERSION}.zip
      displayName: unzip KRE package
    - script: Katalon_Studio_Engine_Windows_64-8.0.0\katalonc -noSplash -runMode=console -projectPath="Regression-api-web-combination-sample\Sample Jira ticket creation.prj" -retry=0 -testSuitePath="Test Suites/Create and update a task by both API and UI" -browserType="Chrome" -apiKey="f94fd9eb-459b-4115-8980-e632fb614490"


