name: Run automation
on:  
  push:
    branches:
      - master
# resources
jobs:
  run_automation:
    runs-on: windows-latest
    steps:
      - name: download ks
      - run: |
          curl "https://download.katalon.com/8.0.0/Katalon_Studio_Engine_Windows_64-8.0.0.zip" -o "katalon_runtime_engine.zip"
      - name: unzip
      - run: |
          unzip katalon_runtime_engine.zip
      - name: clone project
      - run: |
          git clone https://github.com/kms-loantran/Regression-api-web-combination-sample.git
      - name: run ks
      - run: |
        Katalon_Studio_Engine_Windows_64-8.0.0\katalonc -noSplash -runMode=console -projectPath="Regression-api-web-combination-sample\Sample Jira ticket creation.prj" -retry=0 -testSuitePath="Test Suites/Create and update a task by both API and UI" -browserType="Chrome" -apiKey="f94fd9eb-459b-4115-8980-e632fb614490"