version: 0.2
env:
  secrets-manager:
    KATALON_API_KEY: CodebuildDemo:KATALON_API_KEY
phases:
  pre_build:
    commands:
      - docker pull katalonstudio/katalon:test
  build:
    commands:
      - docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon katalonc.sh -projectPath=/tmp/project -apiKey=$KATALON_API_KEY -browserType="Chrome" -retry=0 -retryStrategy=immediately -testSuitePath="Test Suites/google test" --config -webui.autoUpdateDrivers=true